# Generated by Django 3.1.4 on 2021-02-25 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
