# Generated by Django 3.1.4 on 2021-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210224_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('planos', models.CharField(choices=[('PRO', 'PRO'), ('PLUS', 'PLUS'), ('PREMIUM', 'PREMIUM')], max_length=50, verbose_name='Planos')),
                ('descricao', models.TextField(max_length=150, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-package', 'Box'), ('lni-drop', 'Drop'), ('lni-star', 'Star')], max_length=50, verbose_name='ícone')),
                ('precos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preços')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
    ]
