# Generated by Django 3.1.4 on 2021-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preco',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='icone',
            field=models.CharField(choices=[('lni-star-filled', 'Estrela'), ('lni-star-half', 'Estrela 2')], max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='icone',
            field=models.CharField(choices=[('lni-package', 'Box'), ('lni-drop', 'Drop'), ('lni-star', 'Star')], max_length=50, verbose_name='Ícone'),
        ),
    ]
