# Generated by Django 3.1.4 on 2021-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210225_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descrricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-rocket', 'Rocket'), ('lni-laptop-phone', 'Laptop-Phone'), ('lni-cog', 'Cog'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Layers')], max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
