# Generated by Django 3.1.4 on 2021-02-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recurso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='descrricao',
            new_name='descricao',
        ),
    ]
